// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class DetallePedido
{
    public int DetallePedidoId { get; set; }

    public int? PedidoId { get; set; }

    public int? ProductoId { get; set; }

    public decimal? Cantidad { get; set; }

    public decimal? ValorUnitario { get; set; }

    public decimal? ValorTotal { get; set; }

    public virtual Pedido Pedido { get; set; }
}