// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class EstadoPedido
{
    public int EstadoPedidoId { get; set; }

    public string NombreEstadoPedido { get; set; }

    public virtual ICollection<Pedido> Pedido { get; set; } = new List<Pedido>();
}