// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Historialtomafisica
{
    public int HistorialTomaFisicaId { get; set; }

    public DateTime FechaInicio { get; set; }

    public bool Vigente { get; set; }

    public virtual ICollection<Detallehistorialtomafisica> Detallehistorialtomafisica { get; set; } = new List<Detallehistorialtomafisica>();
}