// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MabrukBlazor2026.Shared.ModelsInventario;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial interface IMabrukInventarioContextProcedures
    {
        Task<int> sp_actualizar_clienteAsync(int? clienteId, string nombreComercial, string nIT, string direccionComercial, string telefonos, string correoElectronico, string contactoPrincipal, string telContacto, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_actualizar_detalle_pedidoAsync(int? pedidoID, int? productoID, decimal? cantidad, decimal? valor_Unitario, decimal? valor_Total, OutputParameter<int?> detallePedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_buscar_clienteResult>> sp_buscar_clienteAsync(string criterio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_buscar_productoResult>> sp_buscar_productoAsync(string criterio, int? marcaId, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_buscar_producto_clienteResult>> sp_buscar_producto_clienteAsync(int? clienteID, int? marcaId, string criterio, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_cambiar_es_cotizacionAsync(int? pedidoID, bool? es_Cotizacion, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_comparar_pedidoAsync(int? pedidoID, OutputParameter<int?> nivel_Similitud, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_confirmar_pedidoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_eliminar_detalle_pedidoAsync(int? detallePedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_eliminar_pedidoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_enviar_correoResult>> sp_enviar_correoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_establecer_eliminadaAsync(int? notifiacionID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_Establecer_LeidaAsync(int? notificacionId, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_error_infoResult>> sp_get_error_infoAsync(int? numero, int? version, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_iniciar_pedidoAsync(int? clienteID, string vendedorID, bool? esCotizacion, OutputParameter<int?> pedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_Iniciar_TomaFisicaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Listado_Notificaciones_UsuarioResult>> sp_Listado_Notificaciones_UsuarioAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_listado_pedidosResult>> sp_listado_pedidosAsync(string usuario, int? tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_notificarAsync(int? usuarioNotificaID, string textoAbreviado, string descripcion, OutputParameter<int?> notificacionID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_clienteResult>> sp_obtener_clienteAsync(int? clienteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_detalle_pedidoResult>> sp_obtener_detalle_pedidoAsync(int? detallePedidoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_errorResult>> sp_obtener_errorAsync(int? numero, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_notificacionResult>> sp_obtener_notificacionAsync(int? notificacionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Obtener_Notificaciones_PendientesResult>> sp_Obtener_Notificaciones_PendientesAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_pedidoResult>> sp_obtener_pedidoAsync(int? pedidoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_obtener_productoResult>> sp_obtener_productoAsync(int? productoId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
