// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MabrukBlazor2026.Shared.ModelsInventario;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class MabrukInventarioContext
    {
        private IMabrukInventarioContextProcedures _procedures;

        public virtual IMabrukInventarioContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MabrukInventarioContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMabrukInventarioContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MabrukInventarioContextProcedures : IMabrukInventarioContextProcedures
    {
        private readonly MabrukInventarioContext _context;

        public MabrukInventarioContextProcedures(MabrukInventarioContext context)
        {
            _context = context;
        }

        public virtual async Task<int> sp_actualizar_clienteAsync(int? clienteId, string nombreComercial, string nIT, string direccionComercial, string telefonos, string correoElectronico, string contactoPrincipal, string telContacto, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClienteId",
                    Value = clienteId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "NombreComercial",
                    Size = 250,
                    Value = nombreComercial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "NIT",
                    Size = 100,
                    Value = nIT ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "DireccionComercial",
                    Size = 500,
                    Value = direccionComercial ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Telefonos",
                    Size = 100,
                    Value = telefonos ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "CorreoElectronico",
                    Size = 100,
                    Value = correoElectronico ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "ContactoPrincipal",
                    Size = 100,
                    Value = contactoPrincipal ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "TelContacto",
                    Size = 50,
                    Value = telContacto ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_actualizar_cliente] @ClienteId = @ClienteId, @NombreComercial = @NombreComercial, @NIT = @NIT, @DireccionComercial = @DireccionComercial, @Telefonos = @Telefonos, @CorreoElectronico = @CorreoElectronico, @ContactoPrincipal = @ContactoPrincipal, @TelContacto = @TelContacto, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_actualizar_detalle_pedidoAsync(int? pedidoID, int? productoID, decimal? cantidad, decimal? valor_Unitario, decimal? valor_Total, OutputParameter<int?> detallePedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterDetallePedidoID = new SqlParameter
            {
                ParameterName = "DetallePedidoID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = detallePedidoID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterDetallePedidoID,
                new SqlParameter
                {
                    ParameterName = "ProductoID",
                    Value = productoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Cantidad",
                    Precision = 18,
                    Scale = 2,
                    Value = cantidad ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Valor_Unitario",
                    Precision = 18,
                    Scale = 2,
                    Value = valor_Unitario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                new SqlParameter
                {
                    ParameterName = "Valor_Total",
                    Precision = 18,
                    Scale = 2,
                    Value = valor_Total ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Decimal,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_actualizar_detalle_pedido] @PedidoID = @PedidoID, @DetallePedidoID = @DetallePedidoID OUTPUT, @ProductoID = @ProductoID, @Cantidad = @Cantidad, @Valor_Unitario = @Valor_Unitario, @Valor_Total = @Valor_Total, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            detallePedidoID?.SetValue(parameterDetallePedidoID.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_buscar_clienteResult>> sp_buscar_clienteAsync(string criterio, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Criterio",
                    Size = 50,
                    Value = criterio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_buscar_clienteResult>("EXEC @returnValue = [dbo].[sp_buscar_cliente] @Criterio = @Criterio", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_buscar_productoResult>> sp_buscar_productoAsync(string criterio, int? marcaId, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Criterio",
                    Size = 20,
                    Value = criterio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MarcaId",
                    Value = marcaId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SoloDisponible",
                    Value = soloDisponible ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_buscar_productoResult>("EXEC @returnValue = [dbo].[sp_buscar_producto] @Criterio = @Criterio, @MarcaId = @MarcaId, @SoloDisponible = @SoloDisponible", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_buscar_producto_clienteResult>> sp_buscar_producto_clienteAsync(int? clienteID, int? marcaId, string criterio, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClienteID",
                    Value = clienteID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MarcaId",
                    Value = marcaId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Criterio",
                    Size = 20,
                    Value = criterio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "SoloDisponible",
                    Value = soloDisponible ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_buscar_producto_clienteResult>("EXEC @returnValue = [dbo].[sp_buscar_producto_cliente] @ClienteID = @ClienteID, @MarcaId = @MarcaId, @Criterio = @Criterio, @SoloDisponible = @SoloDisponible", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_cambiar_es_cotizacionAsync(int? pedidoID, bool? es_Cotizacion, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Es_Cotizacion",
                    Value = es_Cotizacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_cambiar_es_cotizacion] @PedidoID = @PedidoID, @Es_Cotizacion = @Es_Cotizacion, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_comparar_pedidoAsync(int? pedidoID, OutputParameter<int?> nivel_Similitud, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNivel_Similitud = new SqlParameter
            {
                ParameterName = "Nivel_Similitud",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = nivel_Similitud?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterNivel_Similitud,
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_comparar_pedido] @PedidoID = @PedidoID, @Nivel_Similitud = @Nivel_Similitud OUTPUT, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            nivel_Similitud?.SetValue(parameterNivel_Similitud.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_confirmar_pedidoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 100,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_confirmar_pedido] @PedidoID = @PedidoID, @Usuario = @Usuario, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_eliminar_detalle_pedidoAsync(int? detallePedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DetallePedidoID",
                    Value = detallePedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_eliminar_detalle_pedido] @DetallePedidoID = @DetallePedidoID, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_eliminar_pedidoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 50,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_eliminar_pedido] @PedidoID = @PedidoID, @Usuario = @Usuario, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_enviar_correoResult>> sp_enviar_correoAsync(int? pedidoID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 100,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_enviar_correoResult>("EXEC @returnValue = [dbo].[sp_enviar_correo] @PedidoID = @PedidoID, @Usuario = @Usuario, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_establecer_eliminadaAsync(int? notifiacionID, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NotifiacionID",
                    Value = notifiacionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 50,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_establecer_eliminada] @NotifiacionID = @NotifiacionID, @Usuario = @Usuario, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_Establecer_LeidaAsync(int? notificacionId, string usuario, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NotificacionId",
                    Value = notificacionId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 50,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_Establecer_Leida] @NotificacionId = @NotificacionId, @Usuario = @Usuario, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_get_error_infoResult>> sp_get_error_infoAsync(int? numero, int? version, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Numero",
                    Value = numero ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Version",
                    Value = version ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_get_error_infoResult>("EXEC @returnValue = [dbo].[sp_get_error_info] @Numero = @Numero, @Version = @Version", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_iniciar_pedidoAsync(int? clienteID, string vendedorID, bool? esCotizacion, OutputParameter<int?> pedidoID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterPedidoID = new SqlParameter
            {
                ParameterName = "PedidoID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = pedidoID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterPedidoID,
                new SqlParameter
                {
                    ParameterName = "ClienteID",
                    Value = clienteID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "VendedorID",
                    Size = 50,
                    Value = vendedorID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "EsCotizacion",
                    Value = esCotizacion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_iniciar_pedido] @PedidoID = @PedidoID OUTPUT, @ClienteID = @ClienteID, @VendedorID = @VendedorID, @EsCotizacion = @EsCotizacion, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            pedidoID?.SetValue(parameterPedidoID.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_Iniciar_TomaFisicaAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_Iniciar_TomaFisica]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Listado_Notificaciones_UsuarioResult>> sp_Listado_Notificaciones_UsuarioAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Cuenta",
                    Size = 250,
                    Value = cuenta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Listado_Notificaciones_UsuarioResult>("EXEC @returnValue = [dbo].[sp_Listado_Notificaciones_Usuario] @Cuenta = @Cuenta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_listado_pedidosResult>> sp_listado_pedidosAsync(string usuario, int? tipo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Usuario",
                    Size = 50,
                    Value = usuario ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Tipo",
                    Value = tipo ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_listado_pedidosResult>("EXEC @returnValue = [dbo].[sp_listado_pedidos] @Usuario = @Usuario, @Tipo = @Tipo", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_notificarAsync(int? usuarioNotificaID, string textoAbreviado, string descripcion, OutputParameter<int?> notificacionID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNotificacionID = new SqlParameter
            {
                ParameterName = "NotificacionID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = notificacionID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterNotificacionID,
                new SqlParameter
                {
                    ParameterName = "UsuarioNotificaID",
                    Value = usuarioNotificaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "TextoAbreviado",
                    Size = 500,
                    Value = textoAbreviado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Descripcion",
                    Size = -1,
                    Value = descripcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_notificar] @NotificacionID = @NotificacionID OUTPUT, @UsuarioNotificaID = @UsuarioNotificaID, @TextoAbreviado = @TextoAbreviado, @Descripcion = @Descripcion, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            notificacionID?.SetValue(parameterNotificacionID.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_clienteResult>> sp_obtener_clienteAsync(int? clienteID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ClienteID",
                    Value = clienteID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_clienteResult>("EXEC @returnValue = [dbo].[sp_obtener_cliente] @ClienteID = @ClienteID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_detalle_pedidoResult>> sp_obtener_detalle_pedidoAsync(int? detallePedidoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DetallePedidoID",
                    Value = detallePedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_detalle_pedidoResult>("EXEC @returnValue = [dbo].[sp_obtener_detalle_pedido] @DetallePedidoID = @DetallePedidoID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_errorResult>> sp_obtener_errorAsync(int? numero, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Numero",
                    Value = numero ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_errorResult>("EXEC @returnValue = [dbo].[sp_obtener_error] @Numero = @Numero", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_notificacionResult>> sp_obtener_notificacionAsync(int? notificacionID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "NotificacionID",
                    Value = notificacionID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_notificacionResult>("EXEC @returnValue = [dbo].[sp_obtener_notificacion] @NotificacionID = @NotificacionID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Obtener_Notificaciones_PendientesResult>> sp_Obtener_Notificaciones_PendientesAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Cuenta",
                    Size = 250,
                    Value = cuenta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Obtener_Notificaciones_PendientesResult>("EXEC @returnValue = [dbo].[sp_Obtener_Notificaciones_Pendientes] @Cuenta = @Cuenta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_pedidoResult>> sp_obtener_pedidoAsync(int? pedidoID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_pedidoResult>("EXEC @returnValue = [dbo].[sp_obtener_pedido] @PedidoID = @PedidoID", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_obtener_productoResult>> sp_obtener_productoAsync(int? productoId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "ProductoId",
                    Value = productoId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_obtener_productoResult>("EXEC @returnValue = [dbo].[sp_obtener_producto] @ProductoId = @ProductoId", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
