// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class MabrukInventarioContext : DbContext
{
    public MabrukInventarioContext(DbContextOptions<MabrukInventarioContext> options)
        : base(options)
    {
    }

    public virtual DbSet<DetallePedido> DetallePedido { get; set; }

    public virtual DbSet<Detallehistorialtomafisica> Detallehistorialtomafisica { get; set; }

    public virtual DbSet<EstadoPedido> EstadoPedido { get; set; }

    public virtual DbSet<Historialtomafisica> Historialtomafisica { get; set; }

    public virtual DbSet<Notificacion> Notificacion { get; set; }

    public virtual DbSet<Notificacionusuario> Notificacionusuario { get; set; }

    public virtual DbSet<Pedido> Pedido { get; set; }

    public virtual DbSet<Tomafisica> Tomafisica { get; set; }

    public virtual DbSet<Usuariopermiso> Usuariopermiso { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<DetallePedido>(entity =>
        {
            entity.ToTable("detalle_pedido");

            entity.Property(e => e.DetallePedidoId).HasColumnName("DetallePedidoID");
            entity.Property(e => e.Cantidad).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.PedidoId).HasColumnName("PedidoID");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.ValorTotal)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("Valor_Total");
            entity.Property(e => e.ValorUnitario)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("Valor_Unitario");

            entity.HasOne(d => d.Pedido).WithMany(p => p.DetallePedido)
                .HasForeignKey(d => d.PedidoId)
                .HasConstraintName("FK_detalle_pedido_pedido");
        });

        modelBuilder.Entity<Detallehistorialtomafisica>(entity =>
        {
            entity.HasKey(e => e.DetalleHistorialTomaFisicaId).HasName("PK_DetalleHistorialTomaFisica");

            entity.ToTable("detallehistorialtomafisica");

            entity.Property(e => e.DetalleHistorialTomaFisicaId).HasColumnName("DetalleHistorialTomaFisicaID");
            entity.Property(e => e.Cantidad).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.HistorialTomaFisicaId).HasColumnName("HistorialTomaFisicaID");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");

            entity.HasOne(d => d.HistorialTomaFisica).WithMany(p => p.Detallehistorialtomafisica)
                .HasForeignKey(d => d.HistorialTomaFisicaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_DetalleHistorialTomaFisica_HistorialTomaFisica");
        });

        modelBuilder.Entity<EstadoPedido>(entity =>
        {
            entity.ToTable("estado_pedido");

            entity.Property(e => e.EstadoPedidoId).HasColumnName("Estado_PedidoID");
            entity.Property(e => e.NombreEstadoPedido)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Nombre_Estado_Pedido");
        });

        modelBuilder.Entity<Historialtomafisica>(entity =>
        {
            entity.HasKey(e => e.HistorialTomaFisicaId).HasName("PK_HistorialTomaFisica");

            entity.ToTable("historialtomafisica");

            entity.Property(e => e.HistorialTomaFisicaId).HasColumnName("HistorialTomaFisicaID");
            entity.Property(e => e.FechaInicio)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_HistorialTomaFisica_FechaInicio")
                .HasColumnType("datetime");
            entity.Property(e => e.Vigente)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_HistorialTomaFisica_Vigente");
        });

        modelBuilder.Entity<Notificacion>(entity =>
        {
            entity.ToTable("notificacion");

            entity.Property(e => e.NotificacionId).HasColumnName("NotificacionID");
            entity.Property(e => e.Descripcion)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_notificacion_Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.FechaVencimiento)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_notificacion_FechaVencimiento")
                .HasColumnType("datetime");
            entity.Property(e => e.TextoAbreviado)
                .IsRequired()
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.UsuarioNotificaId).HasColumnName("UsuarioNotificaID");
        });

        modelBuilder.Entity<Notificacionusuario>(entity =>
        {
            entity.HasKey(e => new { e.NotificacionId, e.UsuarioId }).HasName("PK_NotificacionUsuario");

            entity.ToTable("notificacionusuario");

            entity.Property(e => e.NotificacionId).HasColumnName("NotificacionID");
            entity.Property(e => e.UsuarioId).HasColumnName("UsuarioID");
            entity.Property(e => e.EstadoId).HasColumnName("EstadoID");
        });

        modelBuilder.Entity<Pedido>(entity =>
        {
            entity.ToTable("pedido");

            entity.Property(e => e.PedidoId).HasColumnName("PedidoID");
            entity.Property(e => e.ClienteId).HasColumnName("ClienteID");
            entity.Property(e => e.DireccionEntrega)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.DocumentoEnvioId).HasColumnName("DocumentoEnvioID");
            entity.Property(e => e.EsCotizacion)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pedido_Es_Cotizacion")
                .HasColumnName("Es_Cotizacion");
            entity.Property(e => e.EstadoPedidoId).HasColumnName("Estado_PedidoID");
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pedido_Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.Observaciones)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.ValorTotal)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_pedido_Valor_Total")
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("Valor_Total");
            entity.Property(e => e.VendedorId)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("VendedorID");

            entity.HasOne(d => d.EstadoPedido).WithMany(p => p.Pedido)
                .HasForeignKey(d => d.EstadoPedidoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_pedido_estado_pedido");
        });

        modelBuilder.Entity<Tomafisica>(entity =>
        {
            entity.HasKey(e => e.TomaFisicaId).HasName("PK_TomaFisica");

            entity.ToTable("tomafisica", tb => tb.HasTrigger("tg_update_tomafisica"));

            entity.Property(e => e.TomaFisicaId).HasColumnName("TomaFisicaID");
            entity.Property(e => e.Cantidad).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Fecha)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TomaFisica_Fecha")
                .HasColumnType("datetime");
            entity.Property(e => e.ProductoId).HasColumnName("ProductoID");
            entity.Property(e => e.Vigente)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_TomaFisica_Vigente");
        });

        modelBuilder.Entity<Usuariopermiso>(entity =>
        {
            entity.HasKey(e => e.UsuarioId);

            entity.ToTable("usuariopermiso");

            entity.Property(e => e.UsuarioId).ValueGeneratedNever();
            entity.Property(e => e.PermitidoDocumentos)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_usuariopermiso_PermitidoDocumentos");
            entity.Property(e => e.PermitidoSubirImagen).HasAnnotation("Relational:DefaultConstraintName", "DF_usuariopermiso_PermitidoSubirImagen");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}