// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Notificacionusuario
{
    public int NotificacionId { get; set; }

    public int UsuarioId { get; set; }

    public int? EstadoId { get; set; }
}