// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Notificacion
{
    public int NotificacionId { get; set; }

    public DateTime Fecha { get; set; }

    public int UsuarioNotificaId { get; set; }

    public string TextoAbreviado { get; set; }

    public string Descripcion { get; set; }

    public DateTime FechaVencimiento { get; set; }
}