// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Pedido
{
    public int PedidoId { get; set; }

    public int ClienteId { get; set; }

    public DateTime Fecha { get; set; }

    public decimal ValorTotal { get; set; }

    public int EstadoPedidoId { get; set; }

    public string VendedorId { get; set; }

    public bool EsCotizacion { get; set; }

    public int? DocumentoEnvioId { get; set; }

    public string Observaciones { get; set; }

    public string DireccionEntrega { get; set; }

    public virtual ICollection<DetallePedido> DetallePedido { get; set; } = new List<DetallePedido>();

    public virtual EstadoPedido EstadoPedido { get; set; }
}