// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_buscar_productoResult
    {
        public int ProductoId { get; set; }
        [StringLength(50)]
        public string Codigo { get; set; }
        [StringLength(2147483647)]
        public string Solo_Nombre { get; set; }
        [StringLength(2147483647)]
        public string NombreProducto { get; set; }
        [Column("ValorUnitario", TypeName = "decimal(10,2)")]
        public decimal? ValorUnitario { get; set; }
        [Column("ValorLista", TypeName = "decimal(10,2)")]
        public decimal? ValorLista { get; set; }
        [Column("Existencia", TypeName = "decimal(38,2)")]
        public decimal Existencia { get; set; }
        [StringLength(50)]
        public string Marca { get; set; }
        [StringLength(50)]
        public string RutaImagen { get; set; }
    }
}
