// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_buscar_clienteResult
    {
        public int ClienteId { get; set; }
        public int? EmpresaId { get; set; }
        public bool? EsPersonaIndividual { get; set; }
        public DateTime? FechaAlta { get; set; }
        [StringLength(250)]
        public string NombreComercial { get; set; }
        [StringLength(50)]
        public string Nit { get; set; }
        [StringLength(500)]
        public string DireccionComercial { get; set; }
        [StringLength(50)]
        public string Telefonos { get; set; }
        [StringLength(50)]
        public string Fax { get; set; }
        [StringLength(250)]
        public string CorreoElectronico { get; set; }
        public bool? Activo { get; set; }
        [StringLength(100)]
        public string RepresentanteLegal { get; set; }
        [StringLength(100)]
        public string ContactoPrincipal { get; set; }
        public bool? TieneCredito { get; set; }
        [Column("LimiteCredito", TypeName = "money")]
        public decimal? LimiteCredito { get; set; }
        public int? DiasCredito { get; set; }
        [Column("SaldoActual", TypeName = "decimal(10,2)")]
        public decimal? SaldoActual { get; set; }
        [Column("SaldoSobregiro", TypeName = "decimal(10,2)")]
        public decimal? SaldoSobregiro { get; set; }
        [StringLength(50)]
        public string TelContacto { get; set; }
        public int? VendedorId { get; set; }
        public bool? ControlInventario { get; set; }
        public int? FrecuenciaRebaja { get; set; }
        public int? CantidadRebaja { get; set; }
        public DateTime? FechaInicio { get; set; }
        public int? MinimoInventario { get; set; }
        public int? Zona { get; set; }
        public int? DepartamentoId { get; set; }
        public int? MunicipioId { get; set; }
        [StringLength(50)]
        public string TerritorioEnMunicipio { get; set; }
        public bool? EnListaNegra { get; set; }
        [StringLength(100)]
        public string Contacto2 { get; set; }
        [StringLength(50)]
        public string TelContacto2 { get; set; }
        [StringLength(2147483647)]
        public string Adicional { get; set; }
        [StringLength(2147483647)]
        public string Adicional2 { get; set; }
        public int? ListadoPrecioId { get; set; }
        [StringLength(250)]
        public string NombreCliente { get; set; }
        [StringLength(250)]
        public string GiroNegocio { get; set; }
        [Column("Porcentaje_Comision", TypeName = "decimal(18,2)")]
        public decimal? Porcentaje_Comision { get; set; }
        [StringLength(100)]
        public string Referencia { get; set; }
    }
}
