// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_enviar_correoResult
    {
    }
}
