// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_get_error_infoResult
    {
        public int ErrorId { get; set; }
        public int? Numero { get; set; }
        [StringLength(500)]
        public string Descripcion { get; set; }
        [StringLength(50)]
        public string Origen { get; set; }
        [StringLength(500)]
        public string Mensaje_Original { get; set; }
    }
}
