// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_Listado_Notificaciones_UsuarioResult
    {
        public int NotificacionID { get; set; }
        public DateTime Fecha { get; set; }
        [StringLength(21)]
        public string Fecha_Str { get; set; }
        public int UsuarioNotificaID { get; set; }
        [StringLength(500)]
        public string TextoAbreviado { get; set; }
        [StringLength(2147483647)]
        public string Descripcion { get; set; }
        public DateTime FechaVencimiento { get; set; }
        [StringLength(21)]
        public string FechaVencimiento_Str { get; set; }
        [StringLength(100)]
        public string UsuarioNotifica { get; set; }
        [StringLength(100)]
        public string Correo_Electronico { get; set; }
    }
}
