// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_listado_pedidosResult
    {
        public int PedidoID { get; set; }
        public int ClienteID { get; set; }
        public DateTime Fecha { get; set; }
        [Column("Valor_Total", TypeName = "decimal(18,2)")]
        public decimal Valor_Total { get; set; }
        public int Estado_PedidoID { get; set; }
        [StringLength(50)]
        public string VendedorID { get; set; }
        public bool Es_Cotizacion { get; set; }
        public int? DocumentoEnvioID { get; set; }
        [StringLength(500)]
        public string Observaciones { get; set; }
        [StringLength(500)]
        public string DireccionEntrega { get; set; }
        [StringLength(10)]
        public string Fecha_Str { get; set; }
        [StringLength(250)]
        public string Nombre_Cliente { get; set; }
        [StringLength(50)]
        public string Nombre_Estado_Pedido { get; set; }
        public int UsuarioId { get; set; }
        [StringLength(100)]
        public string NombreUsuario { get; set; }
        [StringLength(100)]
        public string Correo_Electronico_Vendedor { get; set; }
    }
}
