// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_obtener_notificacionResult
    {
        public int NotificacionID { get; set; }
        public DateTime Fecha { get; set; }
        public int UsuarioNotificaID { get; set; }
        [StringLength(500)]
        public string TextoAbreviado { get; set; }
        [StringLength(2147483647)]
        public string Descripcion { get; set; }
        public DateTime FechaVencimiento { get; set; }
    }
}
