// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_obtener_clienteResult
    {
        public int ClienteId { get; set; }
        [StringLength(250)]
        public string NombreComercial { get; set; }
        [StringLength(50)]
        public string NIT { get; set; }
        [StringLength(500)]
        public string DireccionComercial { get; set; }
        [StringLength(50)]
        public string Telefonos { get; set; }
        [StringLength(250)]
        public string CorreoElectronico { get; set; }
        [StringLength(100)]
        public string ContactoPrincipal { get; set; }
        [StringLength(50)]
        public string TelContacto { get; set; }
    }
}
