// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.ModelsInventario
{
    public partial class sp_obtener_detalle_pedidoResult
    {
        [Column("Cantidad", TypeName = "decimal(18,2)")]
        public decimal? Cantidad { get; set; }
        [Column("Valor_Unitario", TypeName = "decimal(18,2)")]
        public decimal? Valor_Unitario { get; set; }
        [Column("Valor_Total", TypeName = "decimal(18,2)")]
        public decimal? Valor_Total { get; set; }
        public int ProductoId { get; set; }
        [StringLength(50)]
        public string Codigo { get; set; }
        [StringLength(2147483647)]
        public string Solo_Nombre { get; set; }
        [StringLength(2147483647)]
        public string NombreProducto { get; set; }
        [Column("ValorUnitarioProducto", TypeName = "decimal(10,2)")]
        public decimal? ValorUnitarioProducto { get; set; }
        [Column("ValorLista", TypeName = "decimal(10,2)")]
        public decimal? ValorLista { get; set; }
        [Column("Existencia", TypeName = "decimal(38,2)")]
        public decimal Existencia { get; set; }
        [StringLength(50)]
        public string Marca { get; set; }
    }
}
