// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Tomafisica
{
    public int TomaFisicaId { get; set; }

    public int ProductoId { get; set; }

    public decimal Cantidad { get; set; }

    public DateTime Fecha { get; set; }

    public bool Vigente { get; set; }
}