// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.ModelsInventario;

public partial class Usuariopermiso
{
    public int UsuarioId { get; set; }

    public bool PermitidoSubirImagen { get; set; }

    public bool? PermitidoDocumentos { get; set; }
}