// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Cliente
{
    public int ClienteId { get; set; }

    public int? EmpresaId { get; set; }

    public bool? EsPersonaIndividual { get; set; }

    public DateTime? FechaAlta { get; set; }

    public string NombreComercial { get; set; }

    public string Nit { get; set; }

    public string DireccionComercial { get; set; }

    public string Telefonos { get; set; }

    public string Fax { get; set; }

    public string CorreoElectronico { get; set; }

    public bool? Activo { get; set; }

    public string RepresentanteLegal { get; set; }

    public string ContactoPrincipal { get; set; }

    public bool? TieneCredito { get; set; }

    public decimal? LimiteCredito { get; set; }

    public int? DiasCredito { get; set; }

    public decimal? SaldoActual { get; set; }

    public decimal? SaldoSobregiro { get; set; }

    public string TelContacto { get; set; }

    public int? VendedorId { get; set; }

    public bool? ControlInventario { get; set; }

    public int? FrecuenciaRebaja { get; set; }

    public int? CantidadRebaja { get; set; }

    public DateTime? FechaInicio { get; set; }

    public int? MinimoInventario { get; set; }

    public int? Zona { get; set; }

    public int? DepartamentoId { get; set; }

    public int? MunicipioId { get; set; }

    public string TerritorioEnMunicipio { get; set; }

    public bool? EnListaNegra { get; set; }

    public string Contacto2 { get; set; }

    public string TelContacto2 { get; set; }

    public string Adicional { get; set; }

    public string Adicional2 { get; set; }

    public int? ListadoPrecioId { get; set; }

    public string NombreCliente { get; set; }

    public string GiroNegocio { get; set; }

    public decimal? PorcentajeComision { get; set; }

    public string Referencia { get; set; }

    public virtual ICollection<Documentocompra> Documentocompra { get; set; } = new List<Documentocompra>();

    public virtual Usuario Vendedor { get; set; }
}