// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Detalledocumentocompra
{
    public int DetalleDocumentoCompraId { get; set; }

    public int DocumentoCompraId { get; set; }

    public int ProductoId { get; set; }

    public decimal Cantidad { get; set; }

    public decimal? ValorUnitario { get; set; }

    public decimal? ValorTotal { get; set; }

    public decimal? PorcentajeVenta { get; set; }

    public int? NumeroLinea { get; set; }

    public decimal? CantidadVerificacion { get; set; }

    public decimal? CantidadBultos { get; set; }

    public virtual Documentocompra DocumentoCompra { get; set; }

    public virtual ICollection<Inventario> Inventario { get; set; } = new List<Inventario>();

    public virtual Producto Producto { get; set; }
}