// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Detalletomafisica
{
    public int DetalleTomaFisicaId { get; set; }

    public int TomaFisicaId { get; set; }

    public int ProductoId { get; set; }

    public decimal? DisponibleSistema { get; set; }

    public decimal? DisponibleFisico { get; set; }

    public bool Ajustado { get; set; }

    public decimal? Diferencia { get; set; }

    public string Observaciones { get; set; }

    public virtual Producto Producto { get; set; }

    public virtual Tomafisica TomaFisica { get; set; }
}