// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Documentocompra
{
    public int DocumentoCompraId { get; set; }

    public int EmpresaId { get; set; }

    public int? AlmacenId { get; set; }

    public string TipoDocumentoCompraId { get; set; }

    public string NumeroDocumento { get; set; }

    public DateTime Fecha { get; set; }

    public int ProveedorId { get; set; }

    public decimal? Iva { get; set; }

    public decimal? ValorNeto { get; set; }

    public decimal? ValorTotal { get; set; }

    public string EstadoDocumentoId { get; set; }

    public int? MonedaId { get; set; }

    public decimal? PorcentajeVenta { get; set; }

    public decimal? Saldo { get; set; }

    public bool? Credito { get; set; }

    public bool? Anulado { get; set; }

    public DateTime? FechaAnulacion { get; set; }

    public string Observaciones { get; set; }

    public int? DocumentoCobroId { get; set; }

    public int? ClienteId { get; set; }

    public string EstadoVerificacionId { get; set; }

    public decimal TasaCambio { get; set; }

    public decimal? PorcentajeFlete { get; set; }

    public decimal? PorcentajeSeguro { get; set; }

    public virtual Cliente Cliente { get; set; }

    public virtual ICollection<Detalledocumentocompra> Detalledocumentocompra { get; set; } = new List<Detalledocumentocompra>();

    public virtual Proveedor Proveedor { get; set; }

    public virtual Tipodocumento TipoDocumentoCompra { get; set; }

    public virtual ICollection<Tomafisica> Tomafisica { get; set; } = new List<Tomafisica>();
}