// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MabrukBlazor2026.Shared.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MabrukBlazor2026.Shared.Models
{
    public partial interface IMabrukContextProcedures
    {
        Task<List<sp_autenticar_2Result>> sp_autenticar_2Async(string login, string clave, int? version, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_buscar_productoResult>> sp_buscar_productoAsync(string criterio, int? marcaId, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_enviar_correoResult>> sp_enviar_correoAsync(int? documentoEnvioId, int? pedidoID, bool? probar, string copiarA, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_get_error_infoResult>> sp_get_error_infoAsync(int? numero, int? version, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_notificarAsync(int? usuarioNotificaID, string textoAbreviado, string descripcion, OutputParameter<int?> notificacionID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_Obtener_Notificaciones_PendientesResult>> sp_Obtener_Notificaciones_PendientesAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> sp_update_tomafisicaAsync(DateTime? fecha, int? empresaId, int? marcaId, int? usuarioId, OutputParameter<int?> tomaFisicaId, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
