// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Inventario
{
    public int InventarioId { get; set; }

    public int? ProductoId { get; set; }

    public int? DetalleDocumentoCompraId { get; set; }

    public int? AlmacenId { get; set; }

    public decimal? InventarioInicial { get; set; }

    public decimal? InventarioDisponible { get; set; }

    public decimal? ValorUnitarioCompra { get; set; }

    public decimal? ValorUnitarioVenta { get; set; }

    public decimal? ValorTotalCompra { get; set; }

    public decimal? ValorTotalVenta { get; set; }

    public bool? Bloqueada { get; set; }

    public DateTime? TiempoBloqueo { get; set; }

    public Guid? CodigoBloqueo { get; set; }

    public int? UsuarioId { get; set; }

    public string Pc { get; set; }

    public string Ip { get; set; }

    public bool? Pendiente { get; set; }

    public int? UnidadesParciales { get; set; }

    public int? UnidadesCompletas { get; set; }

    public int? EmpresaId { get; set; }

    public virtual Detalledocumentocompra DetalleDocumentoCompra { get; set; }

    public virtual Producto Producto { get; set; }
}