// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MabrukBlazor2026.Shared.ViewModel;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class MabrukContext : DbContext
{
    public MabrukContext(DbContextOptions<MabrukContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Cliente> Cliente { get; set; }

    public virtual DbSet<Detalledocumentocompra> Detalledocumentocompra { get; set; }

    public virtual DbSet<Detalletomafisica> Detalletomafisica { get; set; }

    public virtual DbSet<Documentocompra> Documentocompra { get; set; }

    public virtual DbSet<Inventario> Inventario { get; set; }

    public virtual DbSet<Marca> Marca { get; set; }

    public virtual DbSet<Perfil> Perfil { get; set; }

    public virtual DbSet<Producto> Producto { get; set; }

    public virtual DbSet<Proveedor> Proveedor { get; set; }

    public virtual DbSet<Tipodocumento> Tipodocumento { get; set; }

    public virtual DbSet<Tomafisica> Tomafisica { get; set; }

    public virtual DbSet<Usuario> Usuario { get; set; }


    /**** ADDING VIEWS ******/
    public virtual DbSet<ViewImportDoc> ViewImportDocs { get; set; }

    public virtual DbSet<ProductItemList> ViewProducts { get; set; }

    public virtual DbSet<TakingInventoryItemList> ViewTakeInventory { get; set; }

    public virtual DbSet<VerificationImport> ViewVerificationImport { get; set; }



    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {

        modelBuilder.Entity<ViewImportDoc>(entity => entity.HasNoKey());
        modelBuilder.Entity<ProductItemList>(entity => entity.HasNoKey());
        modelBuilder.Entity<TakingInventoryItemList>(entity => entity.HasNoKey());
        modelBuilder.Entity<VerificationImport>(entity => entity.HasNoKey());



        modelBuilder.Entity<Cliente>(entity =>
        {
            entity.HasKey(e => e.ClienteId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("cliente");

            entity.Property(e => e.Adicional).IsUnicode(false);
            entity.Property(e => e.Adicional2).IsUnicode(false);
            entity.Property(e => e.Contacto2)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.ContactoPrincipal)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CorreoElectronico)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.DepartamentoId)
                .HasDefaultValue(1)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_cliente_DepartamentoId");
            entity.Property(e => e.DireccionComercial)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.EnListaNegra)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_cliente_EnListaNegra");
            entity.Property(e => e.Fax)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaAlta).HasColumnType("datetime");
            entity.Property(e => e.FechaInicio).HasColumnType("datetime");
            entity.Property(e => e.GiroNegocio)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.LimiteCredito).HasColumnType("money");
            entity.Property(e => e.MunicipioId)
                .HasDefaultValue(2)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_cliente_MunicipioId");
            entity.Property(e => e.Nit)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreCliente)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.NombreComercial)
                .HasMaxLength(250)
                .IsUnicode(false);
            entity.Property(e => e.PorcentajeComision)
                .HasColumnType("decimal(18, 2)")
                .HasColumnName("Porcentaje_Comision");
            entity.Property(e => e.Referencia)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.RepresentanteLegal)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.SaldoActual).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.SaldoSobregiro).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TelContacto)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TelContacto2)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Telefonos)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.TerritorioEnMunicipio)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.HasOne(d => d.Vendedor).WithMany(p => p.Cliente)
                .HasForeignKey(d => d.VendedorId)
                .HasConstraintName("FK_cliente_vendedor");
        });

        modelBuilder.Entity<Detalledocumentocompra>(entity =>
        {
            entity.HasKey(e => e.DetalleDocumentoCompraId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("detalledocumentocompra", tb =>
                {
                    tb.HasTrigger("tg_delete_detallecocumentocompra");
                    tb.HasTrigger("tg_update_inventario");
                });

            entity.HasIndex(e => e.DocumentoCompraId, "IDX_DetalleDocumentoCompra").HasFillFactor(80);

            entity.HasIndex(e => e.DocumentoCompraId, "IDX_DetalleDocumentoCompra_DocumentoCompraId").HasFillFactor(80);

            entity.HasIndex(e => e.DocumentoCompraId, "IDX_DetalleDocumentoCompra_DocumentoCompraId2").HasFillFactor(80);

            entity.HasIndex(e => e.ProductoId, "IDX_DetalleDocumentoCompra_ProductoId").HasFillFactor(80);

            entity.Property(e => e.Cantidad).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CantidadBultos).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CantidadVerificacion)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_detalledocumentocompra_CantidadVerificacion")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PorcentajeVenta).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.ValorTotal).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorUnitario).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.DocumentoCompra).WithMany(p => p.Detalledocumentocompra)
                .HasForeignKey(d => d.DocumentoCompraId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_detalledocumentocompra_documentocompra");

            entity.HasOne(d => d.Producto).WithMany(p => p.Detalledocumentocompra)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_detalledocumentocompra_producto");
        });

        modelBuilder.Entity<Detalletomafisica>(entity =>
        {
            entity.HasKey(e => e.DetalleTomaFisicaId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("detalletomafisica");

            entity.Property(e => e.Ajustado).HasAnnotation("Relational:DefaultConstraintName", "DF_detalletomafisica_Ajustado");
            entity.Property(e => e.Diferencia).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DisponibleFisico).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DisponibleSistema).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Observaciones).IsUnicode(false);

            entity.HasOne(d => d.Producto).WithMany(p => p.Detalletomafisica)
                .HasForeignKey(d => d.ProductoId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_detalletomafisica_producto");

            entity.HasOne(d => d.TomaFisica).WithMany(p => p.Detalletomafisica)
                .HasForeignKey(d => d.TomaFisicaId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_detalletomafisica_tomafisica");
        });

        modelBuilder.Entity<Documentocompra>(entity =>
        {
            entity.HasKey(e => e.DocumentoCompraId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("documentocompra");

            entity.HasIndex(e => e.EmpresaId, "IDX_DocumentoCompra_EmpresaId");

            entity.Property(e => e.Anulado)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_documentocompra_Anulado");
            entity.Property(e => e.EstadoDocumentoId)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.EstadoVerificacionId)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Fecha).HasColumnType("datetime");
            entity.Property(e => e.FechaAnulacion)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_documentocompra_FechaAnulacion")
                .HasColumnType("datetime");
            entity.Property(e => e.Iva)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("IVA");
            entity.Property(e => e.NumeroDocumento)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Observaciones).IsUnicode(false);
            entity.Property(e => e.PorcentajeFlete).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PorcentajeSeguro).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.PorcentajeVenta).HasColumnType("decimal(10, 4)");
            entity.Property(e => e.Saldo).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.TasaCambio)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_documentocompra_TasaCambio")
                .HasColumnType("decimal(10, 4)");
            entity.Property(e => e.TipoDocumentoCompraId)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.ValorNeto).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorTotal).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Cliente).WithMany(p => p.Documentocompra)
                .HasForeignKey(d => d.ClienteId)
                .HasConstraintName("FK_documentocompra_cliente");

            entity.HasOne(d => d.Proveedor).WithMany(p => p.Documentocompra)
                .HasForeignKey(d => d.ProveedorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_documentocompra_proveedor");

            entity.HasOne(d => d.TipoDocumentoCompra).WithMany(p => p.Documentocompra)
                .HasForeignKey(d => d.TipoDocumentoCompraId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_documentocompra_tipodocumento");
        });

        modelBuilder.Entity<Inventario>(entity =>
        {
            entity.HasKey(e => e.InventarioId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("inventario");

            entity.HasIndex(e => e.ProductoId, "IDX_Inventario_ProductoId").HasFillFactor(80);

            entity.Property(e => e.Bloqueada)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__inventari__Bloqu__29572725");
            entity.Property(e => e.InventarioDisponible).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.InventarioInicial).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Ip)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IP");
            entity.Property(e => e.Pc)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("PC");
            entity.Property(e => e.Pendiente)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__inventari__Pendi__2A4B4B5E");
            entity.Property(e => e.TiempoBloqueo).HasColumnType("datetime");
            entity.Property(e => e.ValorTotalCompra).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorTotalVenta).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorUnitarioCompra).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorUnitarioVenta).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.DetalleDocumentoCompra).WithMany(p => p.Inventario)
                .HasForeignKey(d => d.DetalleDocumentoCompraId)
                .OnDelete(DeleteBehavior.Cascade)
                .HasConstraintName("FK_inventario_detalledocumentocompra");

            entity.HasOne(d => d.Producto).WithMany(p => p.Inventario)
                .HasForeignKey(d => d.ProductoId)
                .HasConstraintName("FK_inventario_producto");
        });

        modelBuilder.Entity<Marca>(entity =>
        {
            entity.HasKey(e => e.MarcaId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("marca");

            entity.Property(e => e.Marca1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("Marca");
            entity.Property(e => e.Prefijo)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Perfil>(entity =>
        {
            entity.HasKey(e => e.PerfilId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("perfil");

            entity.Property(e => e.Descripcion)
                .HasMaxLength(1000)
                .IsUnicode(false);
            entity.Property(e => e.NombrePerfil)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Producto>(entity =>
        {
            entity.HasKey(e => e.ProductoId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("producto", tb => tb.HasTrigger("tg_update_producto"));

            entity.HasIndex(e => e.EmpresaId, "IDX_Producto_EmpresaId").HasFillFactor(80);

            entity.HasIndex(e => e.EmpresaId, "IDX_Producto_EmpresaId2").HasFillFactor(80);

            entity.Property(e => e.Activo).HasAnnotation("Relational:DefaultConstraintName", "DF_producto_Activo");
            entity.Property(e => e.Arancel)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__producto__Arance__55C4DCB7")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.CantidadMinima).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ClasificacionProducto).HasColumnType("xml");
            entity.Property(e => e.Codigo)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.CodigoProducto)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.CodigoUpc)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("CodigoUPC");
            entity.Property(e => e.Dimensiones)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.FechaAlta).HasColumnType("datetime");
            entity.Property(e => e.Imagen).HasColumnType("image");
            entity.Property(e => e.Manufacturado)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_Manufacturado");
            entity.Property(e => e.NombreProducto)
                .IsRequired()
                .IsUnicode(false);
            entity.Property(e => e.Peso)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasDefaultValueSql("(NULL)")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__producto__Peso__45596AC4");
            entity.Property(e => e.PorcentajeMaximoRebaja)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_PorcentajeMaximoRebaja")
                .HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Producido)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_Producido");
            entity.Property(e => e.RebajaDirecta)
                .HasDefaultValue(true)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_DescuentoDirecto");
            entity.Property(e => e.RebajaParcial)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_DescuentoParcial");
            entity.Property(e => e.RutaImagen)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Servicio)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_producto_Servicio");
            entity.Property(e => e.UnidadesPorCaja)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__producto__Cantid__54D0B87E");
            entity.Property(e => e.ValorCosto).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.ValorCostoSinIva)
                .HasColumnType("decimal(10, 2)")
                .HasColumnName("ValorCostoSinIVA");
            entity.Property(e => e.ValorUnitario)
                .HasDefaultValue(0m)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__producto__ValorU__37A5467C")
                .HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Marca).WithMany(p => p.Producto)
                .HasForeignKey(d => d.MarcaId)
                .HasConstraintName("FK_producto_marca");
        });

        modelBuilder.Entity<Proveedor>(entity =>
        {
            entity.HasKey(e => e.ProveedorId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("proveedor");

            entity.Property(e => e.CuentaId)
                .HasMaxLength(12)
                .IsUnicode(false);
            entity.Property(e => e.DireccionProveedor)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.NitProveedor)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreProveedor)
                .HasMaxLength(250)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Tipodocumento>(entity =>
        {
            entity.HasKey(e => e.TipoDocumentoId).HasName("PK_tipodocumento_1");

            entity.ToTable("tipodocumento");

            entity.Property(e => e.TipoDocumentoId)
                .HasMaxLength(3)
                .IsUnicode(false);
            entity.Property(e => e.Activo)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tipodocumento_Activo");
            entity.Property(e => e.Formato).HasColumnType("xml");
            entity.Property(e => e.GenerarGestion)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tipodocumento_GenerarGestion");
            entity.Property(e => e.RebajaInventario)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tipodocumento_RebajaInventario");
            entity.Property(e => e.TipoDocumento1)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("TipoDocumento");
            entity.Property(e => e.TipoDocumentoFel)
                .HasMaxLength(4)
                .IsUnicode(false)
                .IsFixedLength()
                .HasColumnName("TipoDocumentoFEL");
            entity.Property(e => e.TipoId)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false);
            entity.Property(e => e.VistaEnKardex)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF_tipodocumento_VistaEnKardex");
        });

        modelBuilder.Entity<Tomafisica>(entity =>
        {
            entity.HasKey(e => e.TomaFisicaId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("tomafisica");

            entity.Property(e => e.Estado)
                .HasMaxLength(3)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.Fecha).HasColumnType("datetime");

            entity.HasOne(d => d.DocumentoCompra).WithMany(p => p.Tomafisica)
                .HasForeignKey(d => d.DocumentoCompraId)
                .HasConstraintName("FK_tomafisica_documentocompra");

            entity.HasOne(d => d.Marca).WithMany(p => p.Tomafisica)
                .HasForeignKey(d => d.MarcaId)
                .HasConstraintName("FK_tomafisica_marca");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.UsuarioId).HasAnnotation("SqlServer:FillFactor", 80);

            entity.ToTable("usuario");

            entity.Property(e => e.Abreviatura)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.Clave).HasMaxLength(100);
            entity.Property(e => e.Clave4).HasMaxLength(100);
            entity.Property(e => e.CorreoElectronico)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("Correo_Electronico");
            entity.Property(e => e.EnvioCorreo)
                .HasMaxLength(100)
                .HasColumnName("Envio_Correo");
            entity.Property(e => e.Login)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.NombreUsuario)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PorcentajeComision).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Perfil).WithMany(p => p.Usuario)
                .HasForeignKey(d => d.PerfilId)
                .HasConstraintName("FK_usuario_perfil");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}