// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MabrukBlazor2026.Shared.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace MabrukBlazor2026.Shared.Models
{
    public partial class MabrukContext
    {
        private IMabrukContextProcedures _procedures;

        public virtual IMabrukContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new MabrukContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IMabrukContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class MabrukContextProcedures : IMabrukContextProcedures
    {
        private readonly MabrukContext _context;

        public MabrukContextProcedures(MabrukContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_autenticar_2Result>> sp_autenticar_2Async(string login, string clave, int? version, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Login",
                    Size = 50,
                    Value = login ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Clave",
                    Size = 50,
                    Value = clave ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Version",
                    Value = version ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_autenticar_2Result>("EXEC @returnValue = [dbo].[sp_autenticar_2] @Login = @Login, @Clave = @Clave, @Version = @Version, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_buscar_productoResult>> sp_buscar_productoAsync(string criterio, int? marcaId, bool? soloDisponible, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Criterio",
                    Size = 20,
                    Value = criterio ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "MarcaId",
                    Value = marcaId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "SoloDisponible",
                    Value = soloDisponible ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_buscar_productoResult>("EXEC @returnValue = [dbo].[sp_buscar_producto] @Criterio = @Criterio, @MarcaId = @MarcaId, @SoloDisponible = @SoloDisponible", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_enviar_correoResult>> sp_enviar_correoAsync(int? documentoEnvioId, int? pedidoID, bool? probar, string copiarA, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DocumentoEnvioId",
                    Value = documentoEnvioId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "PedidoID",
                    Value = pedidoID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Probar",
                    Value = probar ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Bit,
                },
                new SqlParameter
                {
                    ParameterName = "CopiarA",
                    Size = 100,
                    Value = copiarA ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_enviar_correoResult>("EXEC @returnValue = [dbo].[sp_enviar_correo] @DocumentoEnvioId = @DocumentoEnvioId, @PedidoID = @PedidoID, @Probar = @Probar, @CopiarA = @CopiarA, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_get_error_infoResult>> sp_get_error_infoAsync(int? numero, int? version, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Numero",
                    Value = numero ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "Version",
                    Value = version ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_get_error_infoResult>("EXEC @returnValue = [dbo].[sp_get_error_info] @Numero = @Numero, @Version = @Version", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_notificarAsync(int? usuarioNotificaID, string textoAbreviado, string descripcion, OutputParameter<int?> notificacionID, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterNotificacionID = new SqlParameter
            {
                ParameterName = "NotificacionID",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = notificacionID?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterNotificacionID,
                new SqlParameter
                {
                    ParameterName = "UsuarioNotificaID",
                    Value = usuarioNotificaID ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "TextoAbreviado",
                    Size = 500,
                    Value = textoAbreviado ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                new SqlParameter
                {
                    ParameterName = "Descripcion",
                    Size = -1,
                    Value = descripcion ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_notificar] @NotificacionID = @NotificacionID OUTPUT, @UsuarioNotificaID = @UsuarioNotificaID, @TextoAbreviado = @TextoAbreviado, @Descripcion = @Descripcion, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            notificacionID?.SetValue(parameterNotificacionID.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_Obtener_Notificaciones_PendientesResult>> sp_Obtener_Notificaciones_PendientesAsync(string cuenta, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "Cuenta",
                    Size = 250,
                    Value = cuenta ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.VarChar,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_Obtener_Notificaciones_PendientesResult>("EXEC @returnValue = [dbo].[sp_Obtener_Notificaciones_Pendientes] @Cuenta = @Cuenta", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<int> sp_update_tomafisicaAsync(DateTime? fecha, int? empresaId, int? marcaId, int? usuarioId, OutputParameter<int?> tomaFisicaId, OutputParameter<string> errMessage, OutputParameter<int?> error, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterTomaFisicaId = new SqlParameter
            {
                ParameterName = "TomaFisicaId",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = tomaFisicaId?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterErrMessage = new SqlParameter
            {
                ParameterName = "ErrMessage",
                Size = 250,
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = errMessage?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.VarChar,
            };
            var parameterError = new SqlParameter
            {
                ParameterName = "Error",
                Direction = System.Data.ParameterDirection.InputOutput,
                Value = error?._value ?? Convert.DBNull,
                SqlDbType = System.Data.SqlDbType.Int,
            };
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterTomaFisicaId,
                new SqlParameter
                {
                    ParameterName = "Fecha",
                    Value = fecha ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.DateTime,
                },
                new SqlParameter
                {
                    ParameterName = "EmpresaId",
                    Value = empresaId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "MarcaId",
                    Value = marcaId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "UsuarioId",
                    Value = usuarioId ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterErrMessage,
                parameterError,
                parameterreturnValue,
            };
            var _ = await _context.Database.ExecuteSqlRawAsync("EXEC @returnValue = [dbo].[sp_update_tomafisica] @TomaFisicaId = @TomaFisicaId OUTPUT, @Fecha = @Fecha, @EmpresaId = @EmpresaId, @MarcaId = @MarcaId, @UsuarioId = @UsuarioId, @ErrMessage = @ErrMessage OUTPUT, @Error = @Error OUTPUT", sqlParameters, cancellationToken);

            tomaFisicaId?.SetValue(parameterTomaFisicaId.Value);
            errMessage?.SetValue(parameterErrMessage.Value);
            error?.SetValue(parameterError.Value);
            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
