// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Marca
{
    public int MarcaId { get; set; }

    public string Marca1 { get; set; }

    public string Prefijo { get; set; }

    public virtual ICollection<Producto> Producto { get; set; } = new List<Producto>();

    public virtual ICollection<Tomafisica> Tomafisica { get; set; } = new List<Tomafisica>();
}