// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Producto
{
    public int ProductoId { get; set; }

    public string Codigo { get; set; }

    public string CodigoProducto { get; set; }

    public string CodigoUpc { get; set; }

    public string NombreProducto { get; set; }

    public int? MarcaId { get; set; }

    public int? UnidadMedidaId { get; set; }

    public string Dimensiones { get; set; }

    public decimal? ValorUnitario { get; set; }

    public decimal? ValorCosto { get; set; }

    public decimal? ValorCostoSinIva { get; set; }

    public byte[] Imagen { get; set; }

    public bool? RebajaDirecta { get; set; }

    public bool? RebajaParcial { get; set; }

    public bool? Manufacturado { get; set; }

    public string ClasificacionProducto { get; set; }

    public DateTime? FechaAlta { get; set; }

    public int? UsuarioIngresoId { get; set; }

    public decimal? PorcentajeMaximoRebaja { get; set; }

    public int? ClaseId { get; set; }

    public int? TipoId { get; set; }

    public int? MaterialId { get; set; }

    public int EmpresaId { get; set; }

    public bool Activo { get; set; }

    public int? LargoImpresion { get; set; }

    public bool? Servicio { get; set; }

    public bool? Producido { get; set; }

    public decimal? CantidadMinima { get; set; }

    public int? SubCategoriaId { get; set; }

    public string RutaImagen { get; set; }

    public int? UnidadesPorCaja { get; set; }

    public decimal? Arancel { get; set; }

    public int? PresentacionId { get; set; }

    public string Peso { get; set; }

    public virtual ICollection<Detalledocumentocompra> Detalledocumentocompra { get; set; } = new List<Detalledocumentocompra>();

    public virtual ICollection<Detalletomafisica> Detalletomafisica { get; set; } = new List<Detalletomafisica>();

    public virtual ICollection<Inventario> Inventario { get; set; } = new List<Inventario>();

    public virtual Marca Marca { get; set; }
}