// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Proveedor
{
    public int ProveedorId { get; set; }

    public string NombreProveedor { get; set; }

    public string NitProveedor { get; set; }

    public string DireccionProveedor { get; set; }

    public int? DiasCredito { get; set; }

    public string CuentaId { get; set; }

    public int? ClienteId { get; set; }

    public virtual ICollection<Documentocompra> Documentocompra { get; set; } = new List<Documentocompra>();
}