// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MabrukBlazor2026.Shared.Models
{
    public partial class sp_autenticar_2Result
    {
        public int UsuarioId { get; set; }
        [StringLength(100)]
        public string NombreUsuario { get; set; }
        [StringLength(50)]
        public string Login { get; set; }
        [StringLength(100)]
        public string Clave { get; set; }
        public bool? Activo { get; set; }
        public int? PerfilId { get; set; }
        public bool? EsVendedor { get; set; }
        public int? VendedorId { get; set; }
        public int? EmpresaId { get; set; }
        [Column("PorcentajeComision", TypeName = "decimal(10,2)")]
        public decimal? PorcentajeComision { get; set; }
        [StringLength(100)]
        public string Clave4 { get; set; }
        [StringLength(100)]
        public string Correo_Electronico { get; set; }
        [StringLength(100)]
        public string Envio_Correo { get; set; }
        [StringLength(5)]
        public string Abreviatura { get; set; }
        [StringLength(50)]
        public string NombrePerfil { get; set; }
        [StringLength(100)]
        public string NombreEmpresa { get; set; }
        public int? AnioAbierto { get; set; }
        public int? MesAbierto { get; set; }
    }
}
