// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Tipodocumento
{
    public string TipoDocumentoId { get; set; }

    public string TipoId { get; set; }

    public string TipoDocumento1 { get; set; }

    public bool? RebajaInventario { get; set; }

    public bool? GenerarGestion { get; set; }

    public bool? VistaEnKardex { get; set; }

    public bool? Activo { get; set; }

    public string Formato { get; set; }

    public bool? GenerarCorrelativoAutomaticamente { get; set; }

    public string TipoDocumentoFel { get; set; }

    public virtual ICollection<Documentocompra> Documentocompra { get; set; } = new List<Documentocompra>();
}