// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Tomafisica
{
    public int TomaFisicaId { get; set; }

    public int? EmpresaId { get; set; }

    public DateTime? Fecha { get; set; }

    public int? UsuarioId { get; set; }

    public int? DocumentoCompraId { get; set; }

    public int? DocumentoEnvioId { get; set; }

    public string Estado { get; set; }

    public int? MarcaId { get; set; }

    public virtual ICollection<Detalletomafisica> Detalletomafisica { get; set; } = new List<Detalletomafisica>();

    public virtual Documentocompra DocumentoCompra { get; set; }

    public virtual Marca Marca { get; set; }
}