// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MabrukBlazor2026.Shared.Models;

public partial class Usuario
{
    public int UsuarioId { get; set; }

    public string NombreUsuario { get; set; }

    public string Login { get; set; }

    public string Clave { get; set; }

    public bool? Activo { get; set; }

    public int? PerfilId { get; set; }

    public bool? EsVendedor { get; set; }

    public int? VendedorId { get; set; }

    public int? EmpresaId { get; set; }

    public decimal? PorcentajeComision { get; set; }

    public string Clave4 { get; set; }

    public string CorreoElectronico { get; set; }

    public string EnvioCorreo { get; set; }

    public string Abreviatura { get; set; }

    public virtual ICollection<Cliente> Cliente { get; set; } = new List<Cliente>();

    public virtual Perfil Perfil { get; set; }
}